# SanctumSpl Pool -- S upgrade path

[[sanctum_lst_list]]
name = ""
symbol = "USDC"
mint = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[sanctum_lst_list.pool]
program = ""
pool = "32D4zRxNc1EssbJieVHfPhZM3rH6CzfUPrWUuWxD9prG"
validator_list = ""
[[sanctum_lst_list]]
name = ""
symbol = "USDT"
mint = "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[sanctum_lst_list.pool]
program = ""
pool = "32D4zRxNc1EssbJieVHfPhZM3rH6CzfUPrWUuWxD9prG"
validator_list = ""
[[sanctum_lst_list]]
name = ""
symbol = "7kbn"
mint = "7kbnvuGBxxj8AG9qp8Scn56muWGaRaFqxg1FsRp3PaFT"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[sanctum_lst_list.pool]
program = ""
pool = "4xqyRGWMRkfVo7GH74aryKjSLcpQiVHGAZY4u1n6wAbZ"
validator_list = ""
[[sanctum_lst_list]]
name = ""
symbol = "EwxN"
mint = "EwxNF8g9UfmsJVcZFTpL9Hx5MCkoQFoJi6XNWzKf1j8e"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[sanctum_lst_list.pool]
program = ""
pool = "6ZLKLjMd2KzH7PPHCXUPgbMAtdTT37VgTtdeXWLoJppr"
validator_list = ""
[[sanctum_lst_list]]
name = ""
symbol = "USDH"
mint = "USDH1SM1ojwWUga67PGrgFWUHibbjqMvuMaDkRJTgkX"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[sanctum_lst_list.pool]
program = ""
pool = "3mZwVQFFngA4PugyLNEgN4b31QHGpX8z1rdBDKK1nW9f"
validator_list = ""
[[sanctum_lst_list]]
name = ""
symbol = "PAI"
mint = "Ea5SjE2Y6yvCeW5dYTn7PYMuW5ikXkvbGdcmSnXeaLjS"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[sanctum_lst_list.pool]
program = ""
pool = "EdCfPu6685kto9w9xJnwyAsrB1xPVcAzLzyVNW9EwdQS"
validator_list = ""
[[sanctum_lst_list]]
name = ""
symbol = "EURC"
mint = "HzwqbKZw8HxMN6bF2yFZNrht3c2iXXzpKcFu7uBEDKtr"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[sanctum_lst_list.pool]
program = ""
pool = "9Z9W39PeFtds3w21mA6QCrJ52TvUo1pt4GSLmGhnPr7G"
validator_list = ""
[[sanctum_lst_list]]
name = ""
symbol = "USH"
mint = "9iLH8T7zoWhY7sBmj1WK9ENbWdS1nL8n9wAxaeRitTa6"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[sanctum_lst_list.pool]
program = ""
pool = "5NLrRmfjaBHj2DpGNihVis6yVv236P8m5AdR838vGMWK"
validator_list = ""
[[sanctum_lst_list]]
name = ""
symbol = "USDC"
mint = "A9mUU4qviSctJVPJdBJWkb28deg915LYJKrzQ19ji3FM"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[sanctum_lst_list.pool]
program = ""
pool = "2X2my7iZEKE7BgqfRVC2a5c5VxekZa2HxGctHyoXxe2m"
validator_list = ""
[[sanctum_lst_list]]
name = ""
symbol = "USDC"
mint = "CR4xnGrhsu1fWNPoX4KbTUUtqGMF3mzRLfj4S6YEs1Yo"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[sanctum_lst_list.pool]
program = ""
pool = "9oie6FvL23gBH1na3M7CUXsRXSpLHaKbMk2vEJaBnNCE"
validator_list = ""
[[sanctum_lst_list]]
name = ""
symbol = "fUSDC"
mint = "Ez2zVjw85tZan1ycnJ5PywNNxR6Gm4jbXQtZKyQNu3Lv"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[sanctum_lst_list.pool]
program = ""
pool = "9ApQCYjzSZ9rjaRFaJX6wCUmn3H977QAJXyAtfk86bbG"
validator_list = ""
[[sanctum_lst_list]]
name = ""
symbol = "USDC"
mint = "J8kcD4Wnd1ehne1dpL8WNtgZQR6Jpui2cTZcrmg5ybAa"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[sanctum_lst_list.pool]
program = ""
pool = "3hGDr9eBCaDnZnXsDZ5aNitzm9xfVn2f6Wp5Gvs47jHP"
validator_list = ""
[[sanctum_lst_list]]
name = ""
symbol = "USDC"
mint = "D6YyAUMTJipLQfUhYs6psdnwpmMz6KbM4Qs9AtCmPpxR"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[sanctum_lst_list.pool]
program = ""
pool = "FM94FtASx7aiKNDQgkbB5byBEEwG4NADiQscNuYkh5jm"
validator_list = ""
[[sanctum_lst_list]]
name = ""
symbol = "USDC"
mint = "HAxCJjnmgkdXhwZYeJiUvBgm4NdQvqhGJCS3KxCnCxWs"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[sanctum_lst_list.pool]
program = ""
pool = "q8V6ZZ6esM7xLVSo8YJd5UbMUXoY4GTGDQV42Wq2yoF"
validator_list = ""
