[[stables_list]]
name = ""
symbol = "USDC"
mint = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[stables_list.pool]
program = ""
pool = "32D4zRxNc1EssbJieVHfPhZM3rH6CzfUPrWUuWxD9prG"
validator_list = ""
[[stables_list]]
name = ""
symbol = "USDT"
mint = "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[stables_list.pool]
program = ""
pool = "32D4zRxNc1EssbJieVHfPhZM3rH6CzfUPrWUuWxD9prG"
validator_list = ""
[[stables_list]]
name = ""
symbol = "UXD"
mint = "7kbnvuGBxxj8AG9qp8Scn56muWGaRaFqxg1FsRp3PaFT"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[stables_list.pool]
program = ""
pool = "4xqyRGWMRkfVo7GH74aryKjSLcpQiVHGAZY4u1n6wAbZ"
validator_list = ""
[[stables_list]]
name = ""
symbol = "acUSD"
mint = "EwxNF8g9UfmsJVcZFTpL9Hx5MCkoQFoJi6XNWzKf1j8e"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[stables_list.pool]
program = ""
pool = "6ZLKLjMd2KzH7PPHCXUPgbMAtdTT37VgTtdeXWLoJppr"
validator_list = ""
[[stables_list]]
name = ""
symbol = "USDH"
mint = "USDH1SM1ojwWUga67PGrgFWUHibbjqMvuMaDkRJTgkX"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[stables_list.pool]
program = ""
pool = "3mZwVQFFngA4PugyLNEgN4b31QHGpX8z1rdBDKK1nW9f"
validator_list = ""
[[stables_list]]
name = ""
symbol = "PAI"
mint = "Ea5SjE2Y6yvCeW5dYTn7PYMuW5ikXkvbGdcmSnXeaLjS"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[stables_list.pool]
program = ""
pool = "EdCfPu6685kto9w9xJnwyAsrB1xPVcAzLzyVNW9EwdQS"
validator_list = ""
[[stables_list]]
name = ""
symbol = "EURC"
mint = "HzwqbKZw8HxMN6bF2yFZNrht3c2iXXzpKcFu7uBEDKtr"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[stables_list.pool]
program = ""
pool = "9Z9W39PeFtds3w21mA6QCrJ52TvUo1pt4GSLmGhnPr7G"
validator_list = ""
[[stables_list]]
name = ""
symbol = "9iLH"
mint = "9iLH8T7zoWhY7sBmj1WK9ENbWdS1nL8n9wAxaeRitTa6"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = ""

[stables_list.pool]
program = ""
pool = "5NLrRmfjaBHj2DpGNihVis6yVv236P8m5AdR838vGMWK"
validator_list = ""
